version: '3'

services:

    DB_Service:
        image: mariadb:latest
        # env_file:
        #     - db.env
        # volumes:
        #     - volume definition
        labels:
            - "traefik.enable=false"
            - "traefik.backend=db"
            - "traefik.docker.network=somenetwork"
        networks:
        - somenetwork

    xmysql:
        image: markuman/xmysql
        networks:
            - somenetwork
        # env_file:
        #     - api.env
        labels:
            - "traefik.backend=mautic_api"
            - "traefik.docker.network=somenetwork"
            - "traefik.enable=true"
            - "traefik.frontend.auth.basic=username:password"
            - "traefik.web.port=80"
            - "traefik.web.frontend.rule=Host:mautic.einmalohnebitte.de;PathPrefixStrip:/api-mautic"

# volumes:
#     - volume1:
#     - volume2:

networks:
  somenetwork:
  # if network is external
  # external: true